version: "3"
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - app-storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: 753c3f3c9ab6ece8996b728bae54a147
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snappy_production
  redis:
    image: redis:7.2.4
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    depends_on:
      - db
      - redis

volumes:
  app-storage:
