version: "3"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://@redis:6379/1
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:13.2-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    logging:
      driver: none

  redis:
    image: redis:6.0.12-alpine
    volumes:
      - redis:/data:delegated
    ports:
      - "6379:6379"
    restart: on-failure
    logging:
      driver: none

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    depends_on:
      - redis
      - postgres

  web:
    <<: *app

    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    depends_on:
      - postgres
      - redis
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  postgresql:
  redis:
