default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin

development:
  <<: *default
  database: snappy_development

test:
  <<: *default
  database: snappy_test

production:
  <<: *default
  database: snappy_production
  username: admin
  password: admin