default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: admin
  host: localhost
  port: 5432

development:
  <<: *default
  database: snappy_development

test:
  <<: *default
  database: snappy_test

production:
  <<: *default
  database: snappy_production
